# Generated by Django 6.0.5 on 2026-05-09 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł kursu')),
                ('description', models.TextField(verbose_name='Opis')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Tytuł lekcji')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Kategoria')),
                ('expected_time', models.IntegerField(help_text='Przewidywany czas (w minutach)', verbose_name='Czas ukończenia')),
                ('content', models.TextField(verbose_name='Treść lekcji')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Kolejność')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
