# Generated by Django 5.1.4 on 2026-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('content', models.TextField()),
                ('estimated_time', models.IntegerField(help_text='Czas ukończenia w minutach')),
                ('level', models.CharField(default='Poziom 1', max_length=50)),
                ('is_ai_generated', models.BooleanField(default=False)),
                ('session_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
