# Generated by Django 6.0.5 on 2026-05-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='short_description',
            field=models.TextField(blank=True, null=True, verbose_name='Krótki opis (zajawka)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(verbose_name='Główna, pełna treść lekcji'),
        ),
    ]
