# Generated by Django 5.2.7 on 2026-05-10 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_course_id_alter_lesson_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_course_id', models.CharField(blank=True, max_length=100, verbose_name='ID kursu AI')),
                ('course_title', models.CharField(max_length=200, verbose_name='Tytuł kursu')),
                ('user_session_id', models.CharField(max_length=100, verbose_name='ID sesji użytkownika')),
                ('questions', models.JSONField(default=list, verbose_name='Pytania')),
                ('answers', models.JSONField(blank=True, default=dict, verbose_name='Odpowiedzi użytkownika')),
                ('evaluation_result', models.JSONField(blank=True, default=dict, verbose_name='Wynik oceny')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='courses.course', verbose_name='Kurs')),
            ],
        ),
    ]
