# Generated by Django 5.2.7 on 2026-05-10 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_courseassessment'),
        ('courses', '0006_more_security_lessons'),
    ]

    operations = [
    ]
