# Generated by Django 5.1.4 on 2026-05-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('predicted_time', models.IntegerField()),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('directory', models.CharField(max_length=255)),
            ],
        ),
    ]
